[package]
name = "testapp"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.0"
solana-sdk = "1.18.0"
clap = { version = "4.1.0", features = ["derive"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
bs58 = "0.4"